// Generated by gencpp from file mybot_description/MapPoint.msg
// DO NOT EDIT!


#ifndef MYBOT_DESCRIPTION_MESSAGE_MAPPOINT_H
#define MYBOT_DESCRIPTION_MESSAGE_MAPPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace mybot_description
{
template <class ContainerAllocator>
struct MapPoint_
{
  typedef MapPoint_<ContainerAllocator> Type;

  MapPoint_()
    : mapPointID(0)
    , position()
    , angleOfApproach(0.0)  {
    }
  MapPoint_(const ContainerAllocator& _alloc)
    : mapPointID(0)
    , position(_alloc)
    , angleOfApproach(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _mapPointID_type;
  _mapPointID_type mapPointID;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _angleOfApproach_type;
  _angleOfApproach_type angleOfApproach;





  typedef boost::shared_ptr< ::mybot_description::MapPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mybot_description::MapPoint_<ContainerAllocator> const> ConstPtr;

}; // struct MapPoint_

typedef ::mybot_description::MapPoint_<std::allocator<void> > MapPoint;

typedef boost::shared_ptr< ::mybot_description::MapPoint > MapPointPtr;
typedef boost::shared_ptr< ::mybot_description::MapPoint const> MapPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mybot_description::MapPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mybot_description::MapPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mybot_description

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mybot_description': ['/home/varsh/mybot_ws/src/mybot_description/msg', '/home/varsh/mybot_ws/devel/.private/mybot_description/share/mybot_description/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mybot_description::MapPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybot_description::MapPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mybot_description::MapPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mybot_description::MapPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybot_description::MapPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybot_description::MapPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mybot_description::MapPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25d6001ca9760cc13d10b9eb4e3a92e8";
  }

  static const char* value(const ::mybot_description::MapPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25d6001ca9760cc1ULL;
  static const uint64_t static_value2 = 0x3d10b9eb4e3a92e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::mybot_description::MapPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mybot_description/MapPoint";
  }

  static const char* value(const ::mybot_description::MapPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mybot_description::MapPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message file for nodes in map\n\
\n\
uint8 mapPointID\n\
geometry_msgs/Point position\n\
float64 angleOfApproach\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::mybot_description::MapPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mybot_description::MapPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapPointID);
      stream.next(m.position);
      stream.next(m.angleOfApproach);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mybot_description::MapPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mybot_description::MapPoint_<ContainerAllocator>& v)
  {
    s << indent << "mapPointID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mapPointID);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "angleOfApproach: ";
    Printer<double>::stream(s, indent + "  ", v.angleOfApproach);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYBOT_DESCRIPTION_MESSAGE_MAPPOINT_H
