// Generated by gencpp from file mybot_description/NavigateResult.msg
// DO NOT EDIT!


#ifndef MYBOT_DESCRIPTION_MESSAGE_NAVIGATERESULT_H
#define MYBOT_DESCRIPTION_MESSAGE_NAVIGATERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace mybot_description
{
template <class ContainerAllocator>
struct NavigateResult_
{
  typedef NavigateResult_<ContainerAllocator> Type;

  NavigateResult_()
    : goal_image()
    , decision_score(0.0)
    , status(false)  {
    }
  NavigateResult_(const ContainerAllocator& _alloc)
    : goal_image(_alloc)
    , decision_score(0.0)
    , status(false)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _goal_image_type;
  _goal_image_type goal_image;

   typedef double _decision_score_type;
  _decision_score_type decision_score;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::mybot_description::NavigateResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mybot_description::NavigateResult_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateResult_

typedef ::mybot_description::NavigateResult_<std::allocator<void> > NavigateResult;

typedef boost::shared_ptr< ::mybot_description::NavigateResult > NavigateResultPtr;
typedef boost::shared_ptr< ::mybot_description::NavigateResult const> NavigateResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mybot_description::NavigateResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mybot_description::NavigateResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mybot_description

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mybot_description': ['/home/varsh/mybot_ws/src/mybot_description/msg', '/home/varsh/mybot_ws/devel/.private/mybot_description/share/mybot_description/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mybot_description::NavigateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybot_description::NavigateResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mybot_description::NavigateResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mybot_description::NavigateResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybot_description::NavigateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybot_description::NavigateResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mybot_description::NavigateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80cb4215bc51bc550fe50e7808061ee9";
  }

  static const char* value(const ::mybot_description::NavigateResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80cb4215bc51bc55ULL;
  static const uint64_t static_value2 = 0x0fe50e7808061ee9ULL;
};

template<class ContainerAllocator>
struct DataType< ::mybot_description::NavigateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mybot_description/NavigateResult";
  }

  static const char* value(const ::mybot_description::NavigateResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mybot_description::NavigateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#Define the result\n\
sensor_msgs/Image goal_image\n\
float64 decision_score\n\
bool status\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mybot_description::NavigateResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mybot_description::NavigateResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_image);
      stream.next(m.decision_score);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mybot_description::NavigateResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mybot_description::NavigateResult_<ContainerAllocator>& v)
  {
    s << indent << "goal_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_image);
    s << indent << "decision_score: ";
    Printer<double>::stream(s, indent + "  ", v.decision_score);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYBOT_DESCRIPTION_MESSAGE_NAVIGATERESULT_H
