// Generated by gencpp from file mybot_description/NavigateGoal.msg
// DO NOT EDIT!


#ifndef MYBOT_DESCRIPTION_MESSAGE_NAVIGATEGOAL_H
#define MYBOT_DESCRIPTION_MESSAGE_NAVIGATEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mybot_description/MapPoint.h>

namespace mybot_description
{
template <class ContainerAllocator>
struct NavigateGoal_
{
  typedef NavigateGoal_<ContainerAllocator> Type;

  NavigateGoal_()
    : goal_pose()  {
    }
  NavigateGoal_(const ContainerAllocator& _alloc)
    : goal_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mybot_description::MapPoint_<ContainerAllocator>  _goal_pose_type;
  _goal_pose_type goal_pose;





  typedef boost::shared_ptr< ::mybot_description::NavigateGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mybot_description::NavigateGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateGoal_

typedef ::mybot_description::NavigateGoal_<std::allocator<void> > NavigateGoal;

typedef boost::shared_ptr< ::mybot_description::NavigateGoal > NavigateGoalPtr;
typedef boost::shared_ptr< ::mybot_description::NavigateGoal const> NavigateGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mybot_description::NavigateGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mybot_description::NavigateGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mybot_description

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mybot_description': ['/home/varsh/mybot_ws/src/mybot_description/msg', '/home/varsh/mybot_ws/devel/.private/mybot_description/share/mybot_description/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mybot_description::NavigateGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mybot_description::NavigateGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mybot_description::NavigateGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mybot_description::NavigateGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybot_description::NavigateGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mybot_description::NavigateGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mybot_description::NavigateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0907cf9164e93d95a21a0ade9222beb7";
  }

  static const char* value(const ::mybot_description::NavigateGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0907cf9164e93d95ULL;
  static const uint64_t static_value2 = 0xa21a0ade9222beb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::mybot_description::NavigateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mybot_description/NavigateGoal";
  }

  static const char* value(const ::mybot_description::NavigateGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mybot_description::NavigateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the goal\n\
mybot_description/MapPoint goal_pose\n\
\n\
================================================================================\n\
MSG: mybot_description/MapPoint\n\
# Message file for nodes in map\n\
\n\
uint8 mapPointID\n\
geometry_msgs/Point position\n\
float64 angleOfApproach\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::mybot_description::NavigateGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mybot_description::NavigateGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mybot_description::NavigateGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mybot_description::NavigateGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_pose: ";
    s << std::endl;
    Printer< ::mybot_description::MapPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYBOT_DESCRIPTION_MESSAGE_NAVIGATEGOAL_H
